# Generated by Django 3.0.5 on 2020-04-08 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('name', models.TextField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('external_id', models.IntegerField(unique=True)),
                ('external_name', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Firewall_Brand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OnboardingWizard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_start', models.DateField()),
                ('saved_stage', models.IntegerField()),
                ('complete', models.BooleanField()),
                ('f1_client_id', models.IntegerField()),
                ('f1_client_name', models.TextField()),
                ('client_address', models.TextField(default='MISSING ADDR')),
                ('client_phone', models.TextField(default='MISSING PHONE')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Switch_Brand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Switch_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('username', models.TextField()),
                ('userid', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkstationInformation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=500)),
                ('brand', models.CharField(max_length=500)),
                ('model', models.CharField(max_length=500)),
                ('os', models.CharField(max_length=500)),
                ('count', models.IntegerField()),
                ('replace', models.TextField(max_length=500)),
                ('onboarding_id', models.ForeignKey(on_delete=models.SET('0'), to='ict.OnboardingWizard')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServerInformation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=500)),
                ('brand', models.CharField(blank=True, max_length=500)),
                ('model', models.CharField(blank=True, max_length=500)),
                ('os', models.CharField(max_length=500)),
                ('is_vhost', models.BooleanField()),
                ('vhost_os', models.CharField(blank=True, max_length=500)),
                ('onboarding_id', models.ForeignKey(on_delete=models.SET('0'), to='ict.OnboardingWizard')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectDocumentUpload',
            fields=[
                ('title', models.CharField(max_length=500, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('associate_id', models.IntegerField()),
                ('record_type', models.IntegerField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uploaded_by', models.ForeignKey(on_delete=models.SET('0'), related_name='uploaded_documents', to='ict.Users')),
            ],
        ),
        migrations.CreateModel(
            name='PrinterInformation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=500)),
                ('model', models.CharField(max_length=500)),
                ('shared', models.BooleanField()),
                ('onboarding_id', models.ForeignKey(on_delete=models.SET('0'), to='ict.OnboardingWizard')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NetworkInformation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.TextField()),
                ('brand', models.CharField(max_length=500)),
                ('model', models.CharField(max_length=500)),
                ('replace', models.CharField(max_length=500)),
                ('onboarding_id', models.ForeignKey(on_delete=models.SET('0'), to='ict.OnboardingWizard')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Firewall_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('brandid', models.ForeignKey(on_delete=models.SET('0'), to='ict.Firewall_Brand')),
            ],
        ),
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_id', models.IntegerField()),
                ('contact_firstname', models.TextField()),
                ('contact_lastname', models.TextField()),
                ('contact_type', models.IntegerField()),
                ('onboarding_id', models.ForeignKey(on_delete=models.SET('0'), to='ict.OnboardingWizard')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ApplicationInformation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('version', models.CharField(blank=True, max_length=500)),
                ('license', models.CharField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=500)),
                ('criticality', models.CharField(max_length=500)),
                ('onboarding_id', models.ForeignKey(on_delete=models.SET('0'), to='ict.OnboardingWizard')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
